# deploy.yml
name: deploy blog to tencentcloud
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 使用 node:10
      - name: use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      # build
      - name: npm build
        run: |
          npm run build
        env:
          CI: true
  deployment:
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          SOURCE: "dist/"
          ARGS: "-avzr --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/node_modules/"
